name: Auto-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install lftp
    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        echo "$SFTP_HOSTKEY" >> ~/.ssh/known_hosts

    - name: Sync files to Strato
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        lftp -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_HOST <<EOF
        mirror -R ./ /prod
        bye
        EOF
